"""[NEW] Initial migration

Revision ID: b87b98571726
Revises: 
Create Date: 2018-01-16 19:35:30.993169

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b87b98571726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('rsvps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvps',
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='rsvps_event_id_fkey'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rsvps_user_id_fkey'),
                    sa.PrimaryKeyConstraint('user_id', 'event_id', name='rsvps_pkey')
                    )
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"),
                              nullable=False),
                    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('pw_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('events',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('location', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(length=180), autoincrement=False, nullable=True),
                    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='events_owner_fkey'),
                    sa.PrimaryKeyConstraint('id', name='events_pkey'),
                    sa.UniqueConstraint('name', name='events_name_key')
                    )
    # ### end Alembic commands ###
